[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ovos-ocp-bandcamp-plugin"
dynamic = ["version"]
description = "OCP youtube stream extractor plugin"
readme = "README.md"
license = {text = "Apache-2.0"}
authors = [
    {name = "JarbasAi", email = "jarbasai@mailfence.com"}
]
keywords = ["ovos", "ocp", "plugin"]
dependencies = [
    "py_bandcamp",
    "ovos-plugin-manager>=2.1.0,<3.0.0"
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0,<9"
]

[project.urls]
Homepage = "https://github.com/OpenVoiceOS/ovos-ocp-bandcamp-plugin"

[project.entry-points."opm.ocp.extractor"]
"ovos-ocp-bandcamp-plugin" = "ovos_ocp_bandcamp_plugin:OCPBandcampExtractor"

[project.entry-points."opm.ocp.extractor.config"]
"ovos-ocp-bandcamp-plugin.config" = "ovos_ocp_bandcamp_plugin:OCPBandcampExtractorConfig"

[tool.setuptools.dynamic]
version = {attr = "ovos_ocp_bandcamp_plugin.version.__version__"}

[tool.setuptools.packages.find]
where = ["."]
include = ["ovos_ocp_bandcamp_plugin*"]
